# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_kXfuCHmMeFZNy6zWTsGzNuMi5Doqqe
"""

import time

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt

from conv_implementations import naive_conv2d, conv2d_im2col
from depthwise_conv_implementations import depthwise_separable_conv2d, pytorch_depthwise_separable_conv2d


def test_conv_implementation() -> None:
    np.random.seed(42)
    torch.manual_seed(42)

    sizes = [
        (1, 16, 16),
        (1, 28, 28),
        (1, 32, 32),
        (4, 50, 50),
        (3, 64, 64),
        (3, 64, 64),
        (2, 100, 100),
        (3, 128, 128),
        (3, 256, 256),
    ]

    kernels = [
        np.random.randn(2, 1, 3, 3),
        np.random.randn(10, 1, 5, 5),
        np.random.randn(3, 1, 5, 5),
        np.random.randn(8, 4, 3, 3),
        np.random.randn(4, 3, 3, 3),
        np.random.randn(8, 3, 7, 7),
        np.random.randn(4, 2, 1, 1),
        np.random.randn(4, 3, 3, 3),
        np.random.randn(16, 3, 5, 5),
    ]

    numpy_times = []
    im2col_times = []
    size_labels = []
    errors = []

    for size, kernel in zip(sizes, kernels):
        input_np = np.random.randn(*size)
        input_torch = torch.tensor(input_np, dtype=torch.float32)

        start = time.perf_counter()
        out_numpy = naive_conv2d(input_np, kernel, padding=1)
        numpy_time = time.perf_counter() - start

        start = time.perf_counter()
        out_im2col = conv2d_im2col(input_np, kernel, padding=1)
        im2col_time = time.perf_counter() - start

        kernel_torch = torch.tensor(kernel, dtype=torch.float32)
        out_torch = F.conv2d(input_torch.unsqueeze(0), kernel_torch, padding=1)

        try:
            np.testing.assert_allclose(out_numpy, out_im2col, rtol=1e-03, atol=1e-03)
            np.testing.assert_allclose(out_numpy, out_torch.squeeze().numpy(), rtol=1e-03, atol=1e-03)
            error = "OK"
        except AssertionError as e:
            error = f"Ошибка: {str(e).split('\n')[0]}"

        numpy_times.append(numpy_time)
        im2col_times.append(im2col_time)
        size_labels.append(f"{size[1]}x{size[2]}")
        errors.append(error)

        print(f"Размер: {size[1]}x{size[2]} | Numpy: {numpy_time:.4f}s | Im2Col: {im2col_time:.4f}s | Проверка: {error}")

    plt.figure(figsize=(14, 7))
    plt.plot(size_labels, numpy_times, 'o-', label='Numpy реализация', linewidth=2, markersize=8)
    plt.plot(size_labels, im2col_times, 's-', label='Im2Col реализация', linewidth=2, markersize=8)

    for i, error in enumerate(errors):
        if error != "OK":
            plt.annotate(
                        error,
                        xy=(i, max(numpy_times[i], im2col_times[i])),
                        xytext=(0, 20),
                        textcoords='offset points',
                        ha='center',
                        color='red',
                        arrowprops=dict(arrowstyle="->", color='red')
                    )

    plt.title('Сравнение производительности методов свертки', fontsize=14, pad=20)
    plt.xlabel('Размер входного изображения', fontsize=12)
    plt.ylabel('Время выполнения (секунды)', fontsize=12)
    plt.grid(True)
    plt.legend(fontsize=12, loc='upper left')
    plt.tight_layout()


def test_depthwise_conv_implementation() -> None:
    test_cases = [
        (1, 3, 4, 5, 5, 3, 1, 1),
        (2, 1, 2, 4, 4, 3, 1, 0),
        (1, 2, 1, 6, 6, 5, 1, 2),
        (3, 4, 8, 8, 8, 3, 2, 1),
        (1, 3, 3, 7, 7, 1, 1, 0),
    ]

    for case in test_cases:
      batch_size, C_in, C_out, H_in, W_in, kernel_size, stride, padding = case

      print(f"\nТест кейс: batch_size={batch_size}, C_in={C_in}, out={C_out}, "
            f"size={H_in}x{W_in}, kernel={kernel_size}, stride={stride}, padding={padding}")

      input_tensor = torch.randn(batch_size, C_in, H_in, W_in)
      depthwise_filters = torch.randn(C_in, 1, kernel_size, kernel_size)
      pointwise_filters = torch.randn(C_out, C_in, 1, 1)

      output = depthwise_separable_conv2d(
          input_tensor, depthwise_filters, pointwise_filters, stride, padding
      )

      torch_output = pytorch_depthwise_separable_conv2d(
          input_tensor, depthwise_filters, pointwise_filters, stride, padding
      )

      assert output.shape == torch_output.shape, f"Размеры не совпадают: ручная {output.shape}, torch {torch_output.shape}"
      max_diff = (output - torch_output).abs().max().item()
      print(f"Максимальная разница: {max_diff:.6f}")

      if max_diff > 1e-5:
          print("ПЕРВЫЕ 5 ЗНАЧЕНИЙ:")
          print("Ручная:", output[0, 0, :2, :2].detach().numpy().round(4))
          print("PyTorch:", torch_output[0, 0, :2, :2].detach().numpy().round(4))

      assert max_diff < 1e-5, "Результаты не совпадают!"
      print("Тест пройден!")


if __name__ == "__main__":
    test_conv_implementation()
    test_depthwise_conv_implementation()

